apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    database: explainiot
    user: explainiot
    secureJsonData:
      password: explainiot
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: false
